### ISSUE TITLE
Fails to build DatePrototype.cpp.o

### ISSUE THREAD

**Issue by Taqras** [qtwebkit/qtwebkit#1106] opened 2024-05-22 05:28 UTC
```
[ 13%] Building CXX object Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/runtime/DatePrototype.cpp.o
```

<details><summary>snip</summary>

```
In file included from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:36,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/AtomicString.h:378,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/WTFString.h:769,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/interpreter/StackVisitor.h:30,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/interpreter/CallFrame.h:30,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/ArgList.h:25,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/JSObject.h:26,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/JSDestructibleObject.h:4,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/JSWrapperObject.h:25,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/DateInstance.h:24,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/DatePrototype.h:24,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/DatePrototype.cpp:25:
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringView.h:503:35: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  503 |     StringTypeAdapter<StringView>(StringView string)
      |                                   ^~~~~~~~~~
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringView.h:503:35: note: remove the ‘< >’
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:53:28: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
   53 |     StringTypeAdapter<char>(char character)
      |                            ^
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:53:28: note: remove the ‘< >’
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:80:30: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
   80 |     StringTypeAdapter<UChar>(UChar character)
      |                              ^~~~~
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:80:30: note: remove the ‘< >’
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:227:30: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
  227 |     StringTypeAdapter<String>(const String& string)
      |                              ^
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:227:30: note: remove the ‘< >’
In file included from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringConcatenate.h:839:
/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringOperators.h:88:63: warning: template-id not allowed for constructor in C++20 [-Wtemplate-id-cdtor]
   88 |   StringTypeAdapter<StringAppend<StringType1, StringType2>>(StringAppend<StringType1, StringType2>& buffer)
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/WTF/wtf/text/StringOperators.h:88:63: note: remove the ‘< >’
In file included from /usr/include/unicode/uenum.h:25,
                 from /usr/include/unicode/ucal.h:14,
                 from /usr/include/unicode/udat.h:17,
                 from /tmp/qt5-webkit/src/qtwebkit-5.212.0-alpha4/Source/JavaScriptCore/runtime/DatePrototype.cpp:64:
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/usr/include/unicode/localpointer.h:573:76: error: template argument 2 is invalid
  573 | it LocalOpenPointer(std::unique_ptr<Type, decltype(closeFunction)> &&p)
      |                                                                  ^

/usr/include/unicode/localpointer.h:583:78: error: template argument 2 is invalid
  583 | ointer &operator=(std::unique_ptr<Type, decltype(closeFunction)> &&p) {
      |                                                                ^

/usr/include/unicode/localpointer.h:599:59: error: template argument 2 is invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/usr/include/unicode/uenum.h:69:1: note: invalid template non-type parameter
   69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration, uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/ucal.h:803:1: note: invalid template non-type parameter
  803 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUCalendarPointer, UCalendar, ucal_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/uformattable.h:109:1: note: invalid template non-type parameter
  109 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUFormattablePointer, UFormattable, ufmt_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/ufieldpositer.h:83:1: note: invalid template non-type parameter
   83 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUFieldPositionIteratorPointer, UFieldPositionIterator, ufieldpositer_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/unum.h:460:1: note: invalid template non-type parameter
  460 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUNumberFormatPointer, UNumberFormat, unum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/unicode/udat.h:1022:1: note: invalid template non-type parameter
 1022 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUDateFormatPointer, UDateFormat, udat_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

</details>

```
make[2]: *** [Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/build.make:8293: Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/runtime/DatePrototype.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1556: Source/JavaScriptCore/CMakeFiles/JavaScriptCore.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by annulen** [comment] 2024-05-22 09:45
Duplicate of #1105

**Closed as completed by annulen** 2024-05-22 09:45 UTC
