### ISSUE TITLE
Display UI : QTwebkit/QWebview FAILS on W10 but QWebEngineView OK on MacOS

### ISSUE THREAD

**Issue by ThpMop** [qtwebkit/qtwebkit#1049] opened 2021-02-17 09:31 UTC
Hello,
I'm using Qtwebkit with Qt 5.15.1 and mingw8 on Windows10 and WebEngine on Mac OS (Darwin 64) for the same project.

On Mac OS Qt5.14.1, I'm able to display with WebEngineView a ui-template generated by node-red. Here is part of the working code
#include <QWebEngineView>
......
    QWebEngineView *view0 = new QWebEngineView(parent);
    view0->load(QUrl("http://192.168.0.18:1880/ui"));//remote OK
    view0->resize(800,500);//this->width(), this->height()
    view0->show();//OK

On Windows QtWebkit nothing displays
#include <QWebView>
........
    QWebView *view = new QWebView(parent); 
    //view->load(QUrl("file:///E:/nodered/htmlTest.html"));// OK displays
    view->load(QUrl("http://localhost:1880/ui"));
    view->show();// don't show anything

the ui contains css and js code and also woff fonts.
Any suggestion is welcome.
Thanks for your help

**Comment by annulen** [comment] 2021-02-17 09:38
Probably you are using JS features which are not supported in QtWebKit

**Comment by annulen** [comment] 2021-02-17 09:39
Look at messages in JS console to find more info

**Comment by ThpMop** [comment] 2021-02-17 09:45
Thank you, would you mind to tell me which JS console do you refer to?

**Comment by annulen** [comment] 2021-02-17 10:17
You can enable web inspector via QWebSettings::DeveloperExtrasEnabled

**Comment by ThpMop** [comment] 2021-02-17 17:31
Hello,
I added this lines to my code, build is OK and one window is displayed. Should I add more to obtain the JS console ?

     QWebPage *page = view->page();
      page->settings()->setAttribute(QWebSettings::DeveloperExtrasEnabled, true);
      QWebInspector *inspector = new QWebInspector();
      inspector->setVisible(true);
      inspector->setPage(page);
      inspector->show(); // here show a window that corresponds to the view but no console

Would you mind please to tell me where I can find information on the web inspector and how to show the JS console. I made some research but didn't find very much.
Thank you

**Comment by annulen** [comment] 2021-02-17 17:36
>here show a window that corresponds to the view but no console

Do you see UI of Web Inspector in the window? It should have a few tabs, one of them should be console

**Comment by ThpMop** [comment] 2021-02-17 17:37
I just find out that right click on the view shows an inspect button that opens the web inspector where the console is. I'm going to investigate in this direction.

**Comment by ThpMop** [comment] 2021-02-17 17:38
Thanks for the help. I tried with a simple html page that is OK. I'm going to investigate the UI that does not display.

**Comment by ThpMop** [comment] 2021-02-17 18:12
OK it seems as first error that the node-red ui adds a statement ng-include loading.html at the end of the url. then the url is not recognized and causes error 404 (cannot get /ui/loading.html). I'll will try to find a way to get rid of this.
Any idea is welcome.
Thank you

**Comment by annulen** [comment] 2021-02-17 18:16
Does it try to load literally "/ui/loading.html", i.e. without host and protocol? Looks like a failure of url concatenation.

You can also inspect failed network requests on network tab, it allows to see all details which are necessary to reproduce problem with e.g. curl.

**Comment by annulen** [comment] 2021-02-17 18:17
You can also use JS debugger to insert breakpoints and debug your JS code

**Comment by ThpMop** [comment] 2021-02-18 08:00
Yes it seems that it tries to load the /ui/loading.html : the error 404 comes with the loading.html http://127.0.0.1:1880/ui/loading.html
I'm going to check if I can modify the ng-include statement but not sure if it's the good way.

is there an other way to load the url instead of: view->load(QUrl("http://localhost:1880/ui"));

it's strange because on macOS webengine runs the same url properly.

![image](https://user-images.githubusercontent.com/79049829/108322728-1b467e00-71c6-11eb-8770-ac3eecea956b.png)
![image](https://user-images.githubusercontent.com/79049829/108323482-03bbc500-71c7-11eb-9aae-0afbeb8b6181.png)

**Comment by annulen** [comment] 2021-02-18 10:34
Seems like a server-side problem. Could you check what happens if you serve your ui from Windows machine and open it from macOS?

**Comment by ThpMop** [comment] 2021-02-18 13:23
Actually the ui is served from windows with http://127.0.1.1:1880/ui. I can access and read it locally with Edge or firefox for instance but not with Qt5.
I can access and read  it remotely from macOS with safari or another browser and also with the QT5 app build on macOS.

**Comment by ThpMop** [comment] 2021-02-18 15:34
Hello, I applied instructions from https://github.com/node-red/node-red-dashboard#loading-the-dashboardLoading the Dashboard

Now the error 404 is over and there are some JS bugs to correct 

I will let you know.

Due to the size of the dashboard libraries it can take a long time to load if you are running on wireless network. It is possible add a custom loading page if you wish. To do so add a file called loading.html to the node_modules/node-red-dashboard/dist/ folder. A simple example could be

 <div><i class="fa fa-spin fa-5x fa-spinner"></i></div>

**Comment by ThpMop** [comment] 2021-02-21 12:28
Hello,
i solved the problem by node-red coding my ui with uibuilder instead of ui_template.
Now everything is displayed properly
thank you for your help

**Comment by ferdnyc** [comment] 2021-04-18 08:35
@ThpMop If the problem has been resolved downstream (on your end), as the original reporter you're able to indicate that by Closing this issue.

**Closed** 2021-04-18 14:41 UTC
