### ISSUE TITLE
Nasty rendering artifacts, Qt 5.12.3, Windows

### ISSUE THREAD

**Issue by herbmillerjr** [qtwebkit/qtwebkit#815] opened 2019-05-31 14:38 UTC
Haven't the first clue what's causing this. I'll gladly look into it if you can give me a starting point. Does not affect Qt 5.12.2 and under.

![qt5 12 3-google](https://user-images.githubusercontent.com/809065/58713249-2ae9b780-8390-11e9-9ffa-a3b123efa697.PNG)
![qt5 12 3-iw](https://user-images.githubusercontent.com/809065/58713250-2ae9b780-8390-11e9-9516-c766d9872e49.PNG)

**Comment by annulen** [comment] 2019-05-31 14:49
Does it affect other platforms, e.g. Linux? I can check later

Does it reproduce if you take build with 12.2 and replace just Qt5Gui.dll to 12.3 version?

**Comment by annulen** [comment] 2019-05-31 14:54
BTW, there weren't many changes in QtGui in v5.12.2..v5.12.3, I didn't spot anything suspicious

**Comment by annulen** [comment] 2019-05-31 15:07
BTW, were screenshots above produced from clean build?

**Comment by herbmillerjr** [comment] 2019-06-04 14:00
A clean build in the sense that I deleted the WebKitBuild directory and started over, yes. The application doesn't start if I replace the Qt5Gui.dll. I'll give a Linux build of 5.12.3 a shot.

**Comment by annulen** [comment] 2019-06-04 15:25
FWIW I'm using Qt 5.12.3 on Gentoo and see no such artifacts

**Comment by herbmillerjr** [comment] 2019-06-04 20:48
In the process of our diagnosing some other problems, I've discovered this is a VS2019 issue, not a Qt version issue. Qt 5.12.2 compiled with VS2019 has the same problem.

**Comment by annulen** [comment] 2019-06-04 21:32
Do you mean that *Qt compiled with VS2019* makes a problem? What if you mix Qt compiled with 2019 with QtWebKit compiled with 2017, or vice versa?

**Comment by annulen** [comment] 2019-06-04 21:33
2017 and 2019 should be binary compatible, you may even be able to swap dlls

**Comment by kaamui** [comment] 2019-06-05 07:22
MSVC 2019 is not officially supported (or the page is out-to-date)
https://doc.qt.io/qt-5/supported-platforms.html

About that I'm not sure to understand when VS msvc is implied and when Qt msvc is, in the process of compiling qtwebkit on Windows.

**Comment by annulen** [comment] 2019-06-05 22:18
I'm not really sure what rules are for mixing dlls between these compilers. However, described issue may be indeed a result of Qt not being tested with 2019, and may be triggered e,g. by UB or miscompilation domewhere in qtbase

**Comment by annulen** [comment] 2019-06-05 22:21
For debugging, it's better to start from simple HTML test cases. When bug is reproduced, check coordinates passed to QPainter when it's used for drawing lines in GraphicsContextQt. There must be some (0,0) points, because all incorrect lines on screenshot are starting there. If no (0,0) is passed to QPainter, there is a breakage inside Qt code where (0, 0) appears e.g. after transform

**Comment by annulen** [comment] 2019-06-05 22:22
Please check if optimization level affects this bug.

**Comment by annulen** [comment] 2019-06-05 22:39
To prevent wasting time, please make suure that VS2019 is up to date

**Comment by herbmillerjr** [comment] 2019-06-06 00:55
Qt VS2017 + QtWebKit VS2019 is not affected.
Qt VS2019 + QtWebKit VS2017 is affected.

VS2019 was on 16.1.1 before I read this. I can retry with 16.1.2.

**Comment by herbmillerjr** [comment] 2019-06-10 21:41
Qt and QtWebKit build using VS2019 (16.1.2)

QtWebKit is still affected:
![website](https://user-images.githubusercontent.com/809065/59228856-e2f43d00-8ba6-11e9-855f-9e292a7464be.png)

Qt GUI examples are not affected:
![rasterwindow](https://user-images.githubusercontent.com/809065/59228876-eedfff00-8ba6-11e9-9c7d-de83980eca89.PNG)
![analogclock](https://user-images.githubusercontent.com/809065/59228877-eedfff00-8ba6-11e9-81c4-cd2b2a73e9d6.PNG)
![openglwindow](https://user-images.githubusercontent.com/809065/59228878-eedfff00-8ba6-11e9-9fed-00bb4ff478a7.PNG)

**Comment by annulen** [comment] 2019-06-10 21:43
dammit :(

**Comment by annulen** [comment] 2019-06-11 14:20
@herbmillerjr If you need to use VS2019 right now for some reason, we can investigate this, otherwise I propose to delay it until Qt starts making VS2019 builds in CI - maybe issue will be resolved without us

**Comment by vitallium** [comment] 2019-06-26 16:31
Upstream issue - https://bugreports.qt.io/browse/QTBUG-75280

**Comment by vitallium** [comment] 2019-06-26 17:46
Looks like this is an optimization MSVC bug. This patch (from the mentioned issue above) helps.

![image](https://user-images.githubusercontent.com/1894248/60202534-696d7780-9853-11e9-9f05-4a5710d12422.png)

**Comment by annulen** [comment] 2019-06-26 18:09
BTW, I've fixed compilation of full QtWebKit with new revisions of VS2017, and this solution may be reused for qtwebkit-dev as well, so it's likely that use of VS2019 will not be mandatory

**Comment by annulen** [comment] 2019-06-26 18:23
@vitallium I couldn't find a patch in that issue, but many thanks anyway. When huge code base is miscompiled it may be incredibly complex to find a particular function that is causing troubles.

**Comment by herbmillerjr** [comment] 2019-06-27 20:34
MS has taken ownership of the problme. Compiler issue. https://developercommunity.visualstudio.com/content/problem/547684/visual-studio-20191602-generator-incorrect-code-wi.html

**Comment by vitallium** [comment] 2019-11-03 06:38
The upstream issue with MSVC has been resolved - https://developercommunity.visualstudio.com/content/problem/547684/visual-studio-20191602-generator-incorrect-code-wi.html

**Comment by annulen** [comment] 2019-11-03 16:03
Thanks for heads up!

**Closed by annulen** 2019-11-03 16:03 UTC
Labels: upstream issue, windows
