### ISSUE TITLE
QtWebkit-5.212.3-alpha3 mingw gcc 9

### ISSUE THREAD

**Issue by Alexpux** [qtwebkit/qtwebkit#865] opened 2019-07-16 12:51 UTC
Recently released alpha3 sources not buildable with mingw GCC9

**Comment by annulen** [comment] 2019-07-16 12:55
Quite possible because I had to disable MinGW builds because of infrstructure issues. Now these issues are being fixed, and I'll resume MinGW builds soon. If there are errors which can be reproduced with MinGW 7, I'll see them and will try to fix.

But if your errors are specific to GCC 9, please post them here.

**Comment by Alexpux** [comment] 2019-07-16 13:01
I found bug report on Webkit - https://bugs.webkit.org/show_bug.cgi?id=195920
Adopting patch from bug report allow to build 50/50 - gcc crashes time to time in different places. 
Here is my current patch for alpha3 - https://gist.github.com/Alexpux/d1cb2894ab4c2bf33ba33dfae74d9ede

**Comment by Alexpux** [comment] 2019-07-16 15:16
@annulen here build log: https://gofile.io/?c=sQrLHV

**Comment by annulen** [comment] 2019-07-18 19:44
I've just checked GCC 9.1 on Linux and there are no compilation errors.

>I found bug report on Webkit - https://bugs.webkit.org/show_bug.cgi?id=195920

This patch deals with warnings, not errors.

>gcc crashes time to time in different places

And build log includes "internal compiler error". This is clearly a bug in compiler, so you should prepare reduced test case [1] and report it to MinGW developers

[1] https://gcc.gnu.org/wiki/A_guide_to_testcase_reduction

**Comment by annulen** [comment] 2019-07-18 19:46
If gcc crashes are not reproducible, it's likely that compiler itself is miscompiled, or your hardware is unstable

**Comment by Alexpux** [comment] 2019-07-18 19:50
Well we have such problems only with QtWebkit with crashing. I will try to see if I can do anything

**Comment by annulen** [comment] 2019-07-26 22:13
Does it work with GCC 8?

**Comment by Alexpux** [comment] 2019-07-27 09:09
Don’t try

**Comment by annulen** [comment] 2020-03-18 02:44
I think this is fixed in https://github.com/msys2/MINGW-packages/issues/5934

**Closed by annulen** 2020-03-18 02:44 UTC
