### ISSUE TITLE
no docs on building debug version for windows

### ISSUE THREAD

**Issue by Zedsquared** [qtwebkit/qtwebkit#1015] opened 2020-08-06 17:05 UTC
The current windows build instructions don't mention how to get a debug build of qtwebkit. After a normal build following instructions at https://github.com/qtwebkit/qtwebkit/wiki/Building-QtWebKit-on-Windows  I can see no qt5webwidgetsd.dll anywhere, however non debug dlls are present in the package directory.
Also the --install option does not copy the build from the package directory into the qt installation as expected  ... see issue 1009 
How do I debug my qt app that uses qtwebkit?

**Comment by annulen** [comment] 2020-08-07 15:52
As we've found out in IRC channel, issue was caused by using wrong branch (qtwebkit-dev-wip instead of qtwwebkit-5.212). I've added -build_type=Debug to wiki page. Issue 1009 will be investigated separately.

**Closed by annulen** 2020-08-07 15:52 UTC
