### ISSUE TITLE
Font are not rendering

### ISSUE THREAD

**Issue by akshah1989** [qtwebkit/qtwebkit#944] opened 2020-02-18 13:32 UTC
I have build qtwebkit-dev-wip branch with qt5.4.2 and facing issues related to fonts rendering.

1. when I am trying to load https://www.google.com/intl/en-GB/gmail/about/# It fonts and images don't get rendered properly.  

![Screenshot](https://user-images.githubusercontent.com/25096431/74738397-d28b7a80-527c-11ea-84d3-7b8d2135a217.png)

2. I found few test cases which are also not working related to font face.
https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_font-face_rule

![Screenshot-1](https://user-images.githubusercontent.com/25096431/74740268-8e01de00-5280-11ea-815a-7d872916d521.png)

It would be great help if someone can provide any inputs why this is happening.

**Comment by annulen** [comment] 2020-02-18 13:39
Duplicate of #890

**Closed by annulen** 2020-02-18 13:39 UTC

**Comment by annulen** [comment] 2020-02-18 13:51
WebKit has a notion of "simple" and "complex" text rendering paths. If text requires non-trivial shaping for some reason (determined by conditions at https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev-wip/Source/WebCore/platform/graphics/FontCascade.cpp#L623-L657), "complex" path is used, which at the moment is missing a part of implementation

**Comment by akshah1989** [comment] 2020-02-18 14:36
Thanks, for quick response.
Can you provide any workaround bypass system so that we can disable use of all external fonts and use only system fonts so that there will be some text rendering when page gets loaded.

**Comment by annulen** [comment] 2020-02-20 18:51
I'm afraid it's not that simple, it may be easier to fix the bug than work it around
